### ISSUE TITLE
quadsToFacts and factsToQuads do not roundtrip

### ISSUE THREAD

**Issue by yurikhan** [jeswr/hylar-core#155]
**Versions:** hylar-core@1.1.4, rdf-string@1.6.0, n3@1.11.1.

```ts
import { Parser } from 'n3';
import { factsToQuads, quadsToFacts } from 'hylar-core';

const parser = new Parser({ format: 'text/n3' });
const quads = parser.parse(`
@prefix : <#>.
{ :subject :predicate :object } = :graph.
`);

const facts = quadsToFacts(quads);
const quads2 = factsToQuads(facts);
```

**Expected behavior:** `quads`, `facts`, and `quads2` should each contain a representation of two quads:
* subject = `#subject`, predicate = `#predicate`, object = `#object`, graph = some blank node;
* subject = the same blank node, predicate = `http://www.w3.org/2002/07/owl#sameAs`, object = `#graph`, graph = default graph.

**Observed behavior:** `quads` and `facts` as expected; `quads2` contains a representation where both quads have graph = default graph.

**Cause:** `quadToFact` constructs a `Fact` whose `graphs` property [is the original quad’s graph][1] as a Term object, but `factToQuad` [passes that object through `stringToTerm`][2] which expects it to be a string. `stringToTerm` does not find a `.length` property on the graph Term object, concludes it must be an empty string, and [returns the default graph][3].

[1]: https://github.com/jeswr/hylar-core/blob/a9224f222f1b05be1a92b9739da8dfbe8f788093/lib/ParsingInterface.ts#L33
[2]: https://github.com/jeswr/hylar-core/blob/a9224f222f1b05be1a92b9739da8dfbe8f788093/lib/ParsingInterface.ts#L52
[3]: https://github.com/rubensworks/rdf-string.js/blob/80f252757101d45f693899fd33cd138cc845adbe/lib/TermUtil.ts#L94-L96

**Comment by jeswr** [comment]
Thanks for reporting this!

I've created a PR that should resolve this (https://github.com/jeswr/hylar-core/pull/156/files) however I want to add a few more tests to ensure that this does not introduce any breaking changes for how triples are inferenced before merging it to the main branch.

Would this fix introduce any breaking changes in the project you are working on?

**Comment by yurikhan** [comment]
I’m not very far into my project yet. In fact, I am not even sure whether I should try to use proper quads (i.e. rely on the graph property) in my application. I am an absolute noob in RDF and I confess I have not read all available specs.

How is inferencing expected to work across graphs anyway? Suppose:

```
@prefix : <#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.

:Foo a rdfs:Class.
:prop a rdf:Property; rdfs:domain :Foo; :rdfs:range :Foo.

:john :said {:foo :prop :bar}.
```

It looks like a reasoner should be able to infer that `:foo a :Foo. :bar a :Foo.`, but in which graph should those two quads be? Probably not in the default graph because that inference is based on what John said; but also probably not in the graph that represents what John said. Especially if we start inferring from things said by different people.

**Comment by jeswr** [comment]
It [looks like](https://github.com/jeswr/hylar-core/blob/41804e525e07478daa17fce13b0699d72d0958ca/__tests__/graph-test.ts#L19-L36) hylar-core is currently just adding new quads to the default graph (I ran tests on version 1.1.4 and 1.1.5 of hylar-core). When I have time I will look at the original implementation of HyLAR to see if this is the intended behavior or a bug I introduced when extracting the core of the engine (the latter would seem likely).
